name: CI for React and Backend

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Frontend setup
      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install -f

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

      # Backend setup
      - name: Install backend dependencies
        working-directory: ./backend
        run: npm install

      - name: Build backend
        working-directory: ./backend
        run: npm run build

      # Optional: Run backend tests
      # - name: Run backend tests
      #   working-directory: ./backend
      #   run: npm test
